### ISSUE TITLE
Visiting a library content page with many items leads to error

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX-Platform#99]
By marceldev89
```
Unexpected error has occurred
[Command] An unexpected error has occured: Error: The query specified in the URI is not valid. The node count limit of '100' has been exceeded. To increase the limit, set the 'MaxNodeCount' property on EnableQueryAttribute or ODataValidationSettings. (Cause: Unknown) We were notified about the problem.
```

```
Action: Unknown Error
The query specified in the URI is not valid. The node count limit of '100' has been exceeded. To increase the limit, set the 'MaxNodeCount' property on EnableQueryAttribute or ODataValidationSettings.
```

**Comment by sickboy** [comment]
I've implemented the basis of pagination, currently a single page of content will load (max 24 items).

**Comment by Sonsalt** [comment]
User reports on Discord that latest update did not fix the issue for him
